=== Vlady32/xmlTask2/xmlTaskSAX/src/test/resources/SparesXSD.xsd
<?xml version="1.0" encoding="UTF-8"?>
<schema 
  xmlns="http://www.w3.org/2001/XMLSchema" 
  targetNamespace="http://www.example.org/spares" 
  xmlns:tns="http://www.example.org/spares"
  xmlns:xsd="http://www.w3.org/2001/XMLSchema">
  <element name="spares">
    <complexType>
      <sequence>
        <element name="spare" type="tns:Spare" minOccurs="0" maxOccurs="unbounded"/>
      </sequence>
    </complexType>
  </element>
  <complexType name="Spare">
    <sequence>
      <element name="markAuto" type="string"/>
      <element name="modelAuto" type="string"/>
      <element name="cost" type="positiveInteger"/>
    </sequence>
    <attribute name="key" type="ID" use="required"/>
  </complexType>
</schema>

=== Vlady32/xmlTask2/xmlTaskSAX/src/test/resources/anotherTestSpares.xml
<?xml version="1.0" encoding="UTF-8"?><tns:spares xmlns:tns="http://www.example.org/spares" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/spares SparesXSD.xsd">
  <spare key="s1">
    <markAuto>VAZ</markAuto>
    <modelAuto>2101</modelAuto>
    <cost>100000</cost>
  </spare>
  <spare key="s2">
    <markAuto>VW</markAuto>
    <modelAuto>B3</modelAuto>
    <cost>123000</cost>
  </spare>
</tns:spares>

=== Vlady32/xmlTask2/xmlTaskSAX/src/main/resources/Spares.xml
<?xml version="1.0" encoding="UTF-8"?><tns:spares xmlns:tns="http://www.example.org/spares" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/spares sparesXSD.xsd">
  <spare key="s1">
    <markAuto>Audi</markAuto>
    <modelAuto>A6</modelAuto>
    <cost>250000</cost>
  </spare>
  <spare key="s2">
    <markAuto>VW</markAuto>
    <modelAuto>Passat</modelAuto>
    <cost>500000</cost>
  </spare>
  <spare key="s3">
    <markAuto>Mazda</markAuto>
    <modelAuto>626</modelAuto>
    <cost>110000</cost>
  </spare>
</tns:spares>

=== Vlady32/xmlTask2/xmlTaskSAX/src/test/resources/testSpares.xml
<?xml version="1.0" encoding="UTF-8"?><tns:spares xmlns:tns="http://www.example.org/spares" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.example.org/spares SparesXSD.xsd">
  <spare key="s1">
    <markAuto>Volvo</markAuto>
    <modelAuto>S80</modelAuto>
    <cost>125000</cost>
  </spare>
  <spare key="s2">
    <markAuto>Seat</markAuto>
    <modelAuto>Alhambra</modelAuto>
    <cost>5400000</cost>
  </spare>
</tns:spares>
